name: GH-pages workflow

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, closed]

  workflow_dispatch:

jobs:
  # Build job
  gh-pages-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public