name: "Build and Deploy Pull Request Preview Environment"

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, closed]

concurrency: preview-${{ github.ref }}

jobs:
  preview:
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./public
          TARGET_FOLDER: ./public
          CLEAN: true

  notify:
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    needs: [preview]
    steps:
      - name: Comment on pull request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            
            const deploymentUrl = 'https://yao-c.github.io/pr-preview/pr-preview/pr-2/public/';
            const commentBody = `A preview environment has been created: ${deploymentUrl}`;

            const { data: comments } = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: prNumber
            });

            const existingComment = comments.find(comment => comment.body.includes('A preview environment has been created:'));
            if (existingComment) {
              await github.rest.issues.updateComment({
                owner,
                repo,
                comment_id: existingComment.id,
                body: commentBody
              });
            } else {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: commentBody
              });
            }
  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete preview environments 
        run: git push origin --delete gh-pages
        #uses: JamesIves/github-pages-deploy-action@v4
        #with:
          #action: delete
          #branch: gh-pages
          #commit-message: Remove preview for PR 
      
      - name: Leave a comment after removal
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          message: "\
            [PR Preview Action]\
            (${{ github.server_url }}/${{ env.actionrepo }})
            ${{ env.action_version }}
            :---:
            Preview removed because the pull request was closed.
            ${{ env.datetime }}
            "
